
version: 2.1

orbs:
    codecov: codecov/codecov@1.0.4

jobs:
    lint_and_test:
        docker:
            - image: 'misterio92/ci-php-node:latest'
        working_directory: '~/repo'
        steps:
            - 'checkout'
            -
                run:
                    command: 'npm install -g yarn@1.15.2'
            -
                restore_cache:
                    name: 'Cache restore - "./vendor"'
                    keys:
                        - 'v1-dependencies-{{ checksum "composer.lock" }}'
                        - 'v1-dependencies-'
            -
                run:
                    name: 'Build'
                    command: 'composer install --no-interaction'
            -
                save_cache:
                    name: 'Cache save - "./vendor"'
                    paths:
                        - './vendor'
                    key: 'v1-dependencies-{{ checksum "composer.lock" }}'
            -
                run:
                    name: 'Run linters'
                    command: 'bin/robo lint'
            -
                run:
                    name: 'Codeception - unit'
                    command: 'bin/robo test unit'
            -
                run:
                    name: 'Codeception - acceptance'
                    command: 'bin/robo test acceptance'
            -
                store_test_results:
                    path: 'tests/_output/machine/junit'
            -
                codecov/upload:
                    file: 'tests/_output/machine/coverage/*/coverage.xml'

workflows:
    version: 2
    lint_and_test:
        jobs:
            - 'lint_and_test'
